package org.insightech.er.db;

public enum SupportFunction {
	AUTO_INCREMENT,
	AUTO_INCREMENT_SETTING,
	AUTO_INCREMENT_MINVALUE,
	AUTO_INCREMENT_MAXVALUE,
	AUTO_INCREMENT_CACHE,
	AUTO_INCREMENT_CYCLE,
	DESC_INDEX,
	FULLTEXT_INDEX,
	BITMAP_INDEX,
	SCHEMA,
	SEQUENCE,
	SEQUENCE_MINVALUE,
	SEQUENCE_MAXVALUE,
	SEQUENCE_CACHE,
	SEQUENCE_CYCLE,
	SEQUENCE_ORDER,
	COLUMN_UNIT,
	COLUMN_CHARSET,
	ARRAY_TYPE,
	MATERIALIZED_VIEW,
}